In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [8]:
display(a.reshape(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 축이 없는 경우 이런 방법을 사용가능

display(a[None,:])
a[None,:].shape

array([[1, 2, 3, 4, 5, 6]])

(1, 6)

In [14]:
display(a[:,None])
a[:,None].shape

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

(6, 1)

In [15]:
# None만 넣어도 가능

display(a[None])
a[None].shape

array([[1, 2, 3, 4, 5, 6]])

(1, 6)

## ...

In [19]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
display(a[...,0])
display(a[:,0])

array([ 0,  4,  8, 12])

array([ 0,  4,  8, 12])

In [25]:
a = np.arange(16).reshape(2,2,2,2)
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

- 축이 여러개인 경우 유용하다.
- 경우에 따라 축의 수가 다른 array를 받을 수도 있는데 따로 경우를 가정하지 않아도 된다.

In [27]:
display(a[:,:,:,0])
display(a[...,0])

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [28]:
display(a[:,:,0,0])
display(a[...,0,0]) # 축 2개 설정도 된다.

array([[ 0,  4],
       [ 8, 12]])

array([[ 0,  4],
       [ 8, 12]])