In [1]:
import numpy as np

In [4]:
a = np.arange(6).reshape(2,3)
b = np.arange(3)
print(a)
print(b)
print(a*b)

[[0 1 2]
 [3 4 5]]
[0 1 2]
[[ 0  1  4]
 [ 0  4 10]]


In [10]:
a = np.arange(6).reshape(2,3)
b = np.arange(2).reshape(-1,2)
print(a)
print(b)
print(a*b)

[[0 1 2]
 [3 4 5]]
[[0 1]]


ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [7]:
a = np.arange(56).reshape(8,1,7,1)
b = np.arange(15).reshape(3,1,5)
# print(a)
# print(b)
print(a*b)

[[[[  0   0   0   0   0]
   [  0   1   2   3   4]
   [  0   2   4   6   8]
   [  0   3   6   9  12]
   [  0   4   8  12  16]
   [  0   5  10  15  20]
   [  0   6  12  18  24]]

  [[  0   0   0   0   0]
   [  5   6   7   8   9]
   [ 10  12  14  16  18]
   [ 15  18  21  24  27]
   [ 20  24  28  32  36]
   [ 25  30  35  40  45]
   [ 30  36  42  48  54]]

  [[  0   0   0   0   0]
   [ 10  11  12  13  14]
   [ 20  22  24  26  28]
   [ 30  33  36  39  42]
   [ 40  44  48  52  56]
   [ 50  55  60  65  70]
   [ 60  66  72  78  84]]]


 [[[  0   7  14  21  28]
   [  0   8  16  24  32]
   [  0   9  18  27  36]
   [  0  10  20  30  40]
   [  0  11  22  33  44]
   [  0  12  24  36  48]
   [  0  13  26  39  52]]

  [[ 35  42  49  56  63]
   [ 40  48  56  64  72]
   [ 45  54  63  72  81]
   [ 50  60  70  80  90]
   [ 55  66  77  88  99]
   [ 60  72  84  96 108]
   [ 65  78  91 104 117]]

  [[ 70  77  84  91  98]
   [ 80  88  96 104 112]
   [ 90  99 108 117 126]
   [100 110 120 130 140]
   [110 121 1

NumPy에서 요소별 곱셈(element-wise multiplication)을 수행하기 위해서는 두 배열의 형태가 브로드캐스팅(broadcasting) 규칙을 만족해야 합니다.

브로드캐스팅 규칙에 따라, 두 배열의 각 차원은 서로 호환되어야 합니다. 
호환된다는 것은 해당 차원이 같거나 둘 중 하나가 1이어야 한다는 의미입니다. 

차원이 부족한 경우 오른쪽으로 정렬 1을 차원으로 넣어버림